trigger: none
pr: none

parameters:
  - name: teamName
    displayName: 'Select Team Name:    (works only with "development" as target env)'
    default: 'Team-1_Pi'
    type: string
    values:
      - Team-1_Pi
      - Team-2_Wastebusters
      - Team-3_Recyclers
      - Team-4_QA
      - Team-5_Phoenix
      - Team-6_Stig
      - Team-7_Oscar
      - Team-8_Pre-TST
      - Team-9_Ops
      - Team-Laps
      - Team-10_Willow
      - Team-11_Pondscrum
  - name: envToDeploy
    displayName: 'Target env to deploy:    (select "development" for Team1-11)'
    type: string
    values:
      - development
      - tst
      - preprod
      - prod
    default: development

  - name: solutionFolder
    type: string
    default: src

  - name: branchName
    displayName: 'Enter main branch for corresponding migration script (e.g. main-20230627.1) or Release name (e.g. Release-2.8.2)'
    type: string
    default: ''

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:

  - ${{ if eq(parameters.envToDeploy, 'development') }}:
    - template: vars/${{ parameters.teamName }}-${{ parameters.envToDeploy }}.yaml
  - ${{ if eq(parameters.envToDeploy, 'tst') }}:
    - ${{ if ne(parameters.teamName, 'Team-Laps') }}:
      - template: vars/${{ parameters.envToDeploy }}.yaml
    - ${{ if eq(parameters.teamName, 'Team-Laps') }}:
      - template: vars/${{ parameters.teamName }}-${{ parameters.envToDeploy }}.yaml
  - ${{ if eq(parameters.envToDeploy, 'preprod') }}:
    - template: vars/${{ parameters.envToDeploy }}.yaml
  - ${{ if eq(parameters.envToDeploy, 'prod') }}:
    - template: vars/${{ parameters.envToDeploy }}.yaml

resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: feature/342348-update-sql-migration-pipeline

    # The repo will be reference the repo by a release tag (if the branchName parameter contains 'release') otherwise it will pull down the main branch.
    - repository: ReleaseTags
      name: RWD-CPR-EPR4P-ADO/epr-app-config-settings
      type: git
      ref: ${{ replace(replace(contains(parameters.branchName, 'RELEASE'),'True',replace('refs/tags/RELEASETAG','RELEASETAG', parameters.branchName)),'False','main') }}

jobs:
  - job: RunSQLMigrationScript
    displayName: Executing Migration Script
    ${{ if contains(parameters.branchName, 'RELEASE') }}:
      variables:
        # Release tags reference
        - template: pipelines/image-tags/${{ parameters.envToDeploy }}.yaml@ReleaseTags
        - ${{ if eq(parameters.envToDeploy, 'development') }}:
          - template: pipelines/image-tags/${{ parameters.teamName }}-${{ parameters.envToDeploy }}.yaml@ReleaseTags
    steps:
      - template: templates/docker-run-sql-migration.yaml@CommonTemplates
        parameters:
          azureSubscription: $(acr.Subscription)
          solutionFolder: $(solutionFolder)
          projectFolder: $(projectFolder)
          azureContainerRegistryName: $(acr.azureContainerRegistryName)
          repositoryName: $(acr.repositoryName)
          ${{ if contains(parameters.branchName, 'RELEASE') }}:
            branchName: $(DEVRWDWEBWAx407)
          ${{ else }}:
            branchName: ${{ parameters.branchName }}
