variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprprncommonbackend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprprncommonbackendrepository'
  serviceName: 'prdrwdwebwa1418'
  kvName: PRDRWDINFKV1401
  sqlDBserver: 'prdrwddbssq1401.database.windows.net'
  sqlDB: 'prd1_prn'
  acr.Subscription: 'AZR-RWD-PRD1'