variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'epraccreditationbackend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'epraccreditationbackendrepository'
  serviceName: 'prdrwdwebwa1418'
